#spring.application.name=user
spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/userdb
#      database: userdb

#  h2:
#    console:
#      enabled: true
#  datasource:
#      url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

#server:
#  port: 8082


