server:
  port: 8888

spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: /Users/userarpit/Downloads/microservices-projects/ecom-microservices/configserver/src/main/resources/config